/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface QgButton {
        "className": string;
        "disabled": boolean;
        "id": string;
        "size": any;
        "type": HTMLButtonElement["type"];
        "variant": any;
    }
    interface QgCheckbox {
        "className": string;
        "id": string;
    }
    interface QgInput {
        "className": string;
        "description": string;
        "error": string;
        "max": number;
        "min": number;
        "name": string;
        "pattern": string;
        "placeholder": string;
        "required": boolean;
        "type": HTMLInputElement["type"];
    }
    interface QgLabel {
        "class": string;
        "for"?: string;
    }
    interface QgLogo {
        "class"?: string;
        "size": "full" | "icon";
    }
}
declare global {
    interface HTMLQgButtonElement extends Components.QgButton, HTMLStencilElement {
    }
    var HTMLQgButtonElement: {
        prototype: HTMLQgButtonElement;
        new (): HTMLQgButtonElement;
    };
    interface HTMLQgCheckboxElement extends Components.QgCheckbox, HTMLStencilElement {
    }
    var HTMLQgCheckboxElement: {
        prototype: HTMLQgCheckboxElement;
        new (): HTMLQgCheckboxElement;
    };
    interface HTMLQgInputElement extends Components.QgInput, HTMLStencilElement {
    }
    var HTMLQgInputElement: {
        prototype: HTMLQgInputElement;
        new (): HTMLQgInputElement;
    };
    interface HTMLQgLabelElement extends Components.QgLabel, HTMLStencilElement {
    }
    var HTMLQgLabelElement: {
        prototype: HTMLQgLabelElement;
        new (): HTMLQgLabelElement;
    };
    interface HTMLQgLogoElement extends Components.QgLogo, HTMLStencilElement {
    }
    var HTMLQgLogoElement: {
        prototype: HTMLQgLogoElement;
        new (): HTMLQgLogoElement;
    };
    interface HTMLElementTagNameMap {
        "qg-button": HTMLQgButtonElement;
        "qg-checkbox": HTMLQgCheckboxElement;
        "qg-input": HTMLQgInputElement;
        "qg-label": HTMLQgLabelElement;
        "qg-logo": HTMLQgLogoElement;
    }
}
declare namespace LocalJSX {
    interface QgButton {
        "className"?: string;
        "disabled"?: boolean;
        "id"?: string;
        "size"?: any;
        "type"?: HTMLButtonElement["type"];
        "variant"?: any;
    }
    interface QgCheckbox {
        "className"?: string;
        "id"?: string;
    }
    interface QgInput {
        "className"?: string;
        "description"?: string;
        "error"?: string;
        "max"?: number;
        "min"?: number;
        "name"?: string;
        "pattern"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "type"?: HTMLInputElement["type"];
    }
    interface QgLabel {
        "class"?: string;
        "for"?: string;
    }
    interface QgLogo {
        "class"?: string;
        "size"?: "full" | "icon";
    }
    interface IntrinsicElements {
        "qg-button": QgButton;
        "qg-checkbox": QgCheckbox;
        "qg-input": QgInput;
        "qg-label": QgLabel;
        "qg-logo": QgLogo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "qg-button": LocalJSX.QgButton & JSXBase.HTMLAttributes<HTMLQgButtonElement>;
            "qg-checkbox": LocalJSX.QgCheckbox & JSXBase.HTMLAttributes<HTMLQgCheckboxElement>;
            "qg-input": LocalJSX.QgInput & JSXBase.HTMLAttributes<HTMLQgInputElement>;
            "qg-label": LocalJSX.QgLabel & JSXBase.HTMLAttributes<HTMLQgLabelElement>;
            "qg-logo": LocalJSX.QgLogo & JSXBase.HTMLAttributes<HTMLQgLogoElement>;
        }
    }
}
